### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by busycaesar** [busycaesar/MERN_Stack_Template#2]
- [x] Backend: Unit Test
- [x] Backend: Lint Test
- [x] Backend: CI Pipeline for Unit and Lint testing
- [x] Backend: Setup JS Doc with better-docs
- [x] Frontend: Setup JS Doc with better-docs
- [x] Description for settup up JSDoc
- [x] Frontend: Install Bootstrap
- [x] Frontend: Install Tailwind
- [x] Backend: Description for all dependencies and scripts
- [x] Frontend: Description for all dependencies and scripts
- [x] Bifurcate descriptions
